data:
  train_dataset: cifar100
  resize_size: 224
  val_dataset: True
  val_ratio: 0.75

models:
  fine_tune: True
  init_scale: 1.0
  init_threshold: 1.0
  hard_prune: True
  multi_prune: True

training:
  batch_size: 32
  epoch: 50