data:
  train_dataset: imagenette
  train_root: train
  test_root: test
  resize_size: 224
  val_dataset: True
  train_ratio: 0.98

models:
  fine_tune: True
  init_scale: 1.0
  init_scale_threshold: 0.001
  init_sparsity_threshold: 0.9
  multi_prune: True
  granularity: embedding

training:
  batch_size: 128
  epoch: 10
  learning_rate: 0.001
  weight_decay: 0.001
  T_max: 50

energy:
  accuracy_tradeoff: False
  lambda_l1: 0.0000025
  lambda_accuracy: -0.7
  target_accuracy: 0.9
