data:
  train_dataset: cifar100
  resize_size: 224
  val_dataset: True
  val_ratio: 0.99

models:
  fine_tune: True
  init_scale: 1.0
  init_scale_threshold: 0.5
  init_sparsity_threshold: 0.5
  multi_prune: True

training:
  batch_size: 64
  epoch: 10
  learning_rate: 0.01
  weight_decay: 0.09
  T_max: 100

energy:
  lambda_l1: 1.5
  lambda_accuracy: 0.3
  target_accuracy: 0.9
